from bookstation import db
from bookstation.models.user_sys import Goal
from datetime import datetime
db.session.add(Goal(20,datetime(2022,3,26), 5, 0))
db.session.add(Goal(20,datetime(2022,2,15), 8, 6))
db.session.add(Goal(20,datetime(2022,1,12), 2, 5))
db.session.add(Goal(20,datetime(2021,12,5), 0, 1))
db.session.add(Goal(20,datetime(2021,11,24), 3, 3))
db.session.add(Goal(20,datetime(2021,10,17), 3, 2))
db.session.add(Goal(20,datetime(2021,9,26), 1, 2))
db.session.add(Goal(20,datetime(2021,8,26), 5, 4))
db.session.add(Goal(20,datetime(2021,7,26), 2, 3))
db.session.add(Goal(20,datetime(2021,6,26), 7, 8))
db.session.add(Goal(20,datetime(2021,5,26), 0, 0))
db.session.add(Goal(20,datetime(2021,4,26), 2, 1))
db.session.add(Goal(20,datetime(2021,3,26), 3, 4))
db.session.add(Goal(20,datetime(2021,2,26), 2, 2))
db.session.commit()


NEW API FOR NOTIFICATIONS

Need new column in notifications for "seen" (boolean)
Need notification_id if don't have already

ADD ROUTES IN FOLLOWER.PY
notification/setallseen (sets all seen = true in seen column)
input: token

notification/setseen (sets matching notificaton seen = true)
input: token, notification_id

notification/getunread (list of notifications where seen = false)
input: token
output: notifications (will include seen for each notif)

other changes
make getnotifications also return seen for each notif